// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjOk7y6LZscw4qIX1sFdAfIUpJ-BIsDNQ',
    appId: '1:453789642807:web:34b5dcf2a65f42614f0fb2',
    messagingSenderId: '453789642807',
    projectId: 'fir-tutorial-62fa6',
    authDomain: 'fir-tutorial-62fa6.firebaseapp.com',
    storageBucket: 'fir-tutorial-62fa6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoRzJfVMUzsktDwCKTHSoQQvxvnpySdD4',
    appId: '1:453789642807:android:a4dcbc5be324d09c4f0fb2',
    messagingSenderId: '453789642807',
    projectId: 'fir-tutorial-62fa6',
    storageBucket: 'fir-tutorial-62fa6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD13Vlp5mhiNEXqf2lhdOQxTxRGZGwx0IQ',
    appId: '1:453789642807:ios:1840056517c2be444f0fb2',
    messagingSenderId: '453789642807',
    projectId: 'fir-tutorial-62fa6',
    storageBucket: 'fir-tutorial-62fa6.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD13Vlp5mhiNEXqf2lhdOQxTxRGZGwx0IQ',
    appId: '1:453789642807:ios:1840056517c2be444f0fb2',
    messagingSenderId: '453789642807',
    projectId: 'fir-tutorial-62fa6',
    storageBucket: 'fir-tutorial-62fa6.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjOk7y6LZscw4qIX1sFdAfIUpJ-BIsDNQ',
    appId: '1:453789642807:web:a7858631a7451a554f0fb2',
    messagingSenderId: '453789642807',
    projectId: 'fir-tutorial-62fa6',
    authDomain: 'fir-tutorial-62fa6.firebaseapp.com',
    storageBucket: 'fir-tutorial-62fa6.firebasestorage.app',
  );
}
